GET http://127.0.0.1:5000/api/chat/getMessageListBySessionid/5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxNCwiZXhwIjoxNzQ2NjEyMzEwfQ.4Y4As-YByIRl8BwdjRD72qA6AEjn9C6UZ-n-gkZpUms




