PUT http://192.168.34.46:5000/api/account/changePassword
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMCwiZXhwIjoxNzQ2NjAyNjk0fQ.t-mGvdGASfRhiIKmfGEv2Q0b2gJMRCZmLs6qS08HgII

{
  "phonenumber":"16789237652",
  "newPassword":"234",
  "code":123
}




