PUT http://192.168.34.46:5000/api/account/changePhoneNumber
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxNCwiZXhwIjoxNzQ2NjA5OTU3fQ.1_bKhJ2IR_1p6X-VHV0BXyu_brNeyissJ-KpB2jbmkc

{
  "newPhonenumber":"16789237652",
  "code":123
}




